// Known skills and tools for keyword matching. Aliases are other spellings of the same thing,
// so "Postgres" in a resume counts for "PostgreSQL" in a job description.
// caseSensitive is for names that collide with ordinary words ("Go", "S3", "Excel").

export type SkillCategory =
  | "languages"
  | "frontend"
  | "backend"
  | "data"
  | "cloud"
  | "ai"
  | "testing"
  | "practices"
  | "tools"
  | "education";

export type Skill = {
  name: string;
  category: SkillCategory;
  aliases?: string[];
  caseSensitive?: boolean;
};

export const SKILLS: Skill[] = [
  // Languages
  { name: "Python", category: "languages" },
  { name: "Java", category: "languages" },
  { name: "JavaScript", category: "languages", aliases: ["JS", "ECMAScript", "ES6"] },
  { name: "TypeScript", category: "languages", aliases: ["TS"] },
  { name: "C++", category: "languages", aliases: ["CPP"] },
  { name: "C#", category: "languages", aliases: ["CSharp", "C Sharp"] },
  { name: "Go", category: "languages", aliases: ["Golang"], caseSensitive: true },
  { name: "Rust", category: "languages", caseSensitive: true },
  { name: "Kotlin", category: "languages" },
  { name: "Swift", category: "languages", caseSensitive: true },
  { name: "Scala", category: "languages" },
  { name: "Ruby", category: "languages" },
  { name: "PHP", category: "languages" },
  { name: "SQL", category: "languages" },
  { name: "Bash", category: "languages", aliases: ["Shell scripting"] },
  { name: "PowerShell", category: "languages" },
  { name: "HTML", category: "languages", aliases: ["HTML5"] },
  { name: "CSS", category: "languages", aliases: ["CSS3"] },
  { name: "MATLAB", category: "languages" },
  { name: "Perl", category: "languages" },
  { name: "Dart", category: "languages" },
  { name: "Elixir", category: "languages" },
  { name: "Haskell", category: "languages" },

  // Frontend
  { name: "React", category: "frontend", aliases: ["ReactJS", "React.js"] },
  { name: "Next.js", category: "frontend", aliases: ["NextJS"] },
  { name: "Angular", category: "frontend", aliases: ["AngularJS"] },
  { name: "Vue", category: "frontend", aliases: ["Vue.js", "VueJS"] },
  { name: "Svelte", category: "frontend", aliases: ["SvelteKit"] },
  { name: "Redux", category: "frontend" },
  { name: "Tailwind CSS", category: "frontend", aliases: ["Tailwind"] },
  { name: "Sass", category: "frontend", aliases: ["SCSS"] },
  { name: "jQuery", category: "frontend" },
  { name: "Webpack", category: "frontend" },
  { name: "Vite", category: "frontend" },
  { name: "React Native", category: "frontend" },
  { name: "Flutter", category: "frontend" },
  { name: "Accessibility", category: "frontend", aliases: ["a11y", "WCAG"] },
  { name: "Responsive design", category: "frontend" },

  // Backend
  { name: "Node.js", category: "backend", aliases: ["NodeJS", "Node JS"] },
  { name: "Express", category: "backend", aliases: ["Express.js", "ExpressJS"], caseSensitive: true },
  { name: "NestJS", category: "backend", aliases: ["Nest.js"] },
  { name: "Spring Boot", category: "backend", aliases: ["Spring Framework"] },
  { name: "Django", category: "backend" },
  { name: "Flask", category: "backend" },
  { name: "FastAPI", category: "backend" },
  { name: "Ruby on Rails", category: "backend", aliases: ["Rails"] },
  { name: ".NET", category: "backend", aliases: ["dotnet", "ASP.NET", ".NET Core"] },
  { name: "Laravel", category: "backend" },
  { name: "REST APIs", category: "backend", aliases: ["REST", "RESTful", "REST API", "RESTful APIs"] },
  { name: "GraphQL", category: "backend" },
  { name: "gRPC", category: "backend" },
  { name: "Microservices", category: "backend", aliases: ["Microservice", "Micro services"] },
  { name: "Distributed systems", category: "backend", aliases: ["Distributed system"] },
  { name: "System design", category: "backend" },
  { name: "Event-driven architecture", category: "backend", aliases: ["Event-driven", "Event driven"] },
  { name: "API Gateway", category: "backend" },
  { name: "WebSockets", category: "backend", aliases: ["WebSocket"] },
  { name: "Kafka", category: "backend", aliases: ["Apache Kafka"] },
  { name: "RabbitMQ", category: "backend" },
  { name: "Message queues", category: "backend", aliases: ["Message queue", "Message broker"] },
  { name: "Caching", category: "backend", aliases: ["Cache"] },
  { name: "Concurrency", category: "backend", aliases: ["Multithreading", "Multi-threading"] },
  { name: "Authentication", category: "backend", aliases: ["AuthN"] },
  { name: "Authorization", category: "backend", aliases: ["AuthZ"] },
  { name: "OAuth", category: "backend", aliases: ["OAuth2", "OAuth 2.0"] },
  { name: "JWT", category: "backend", aliases: ["JSON Web Token", "JSON Web Tokens"] },
  { name: "RBAC", category: "backend", aliases: ["Role-based access control"] },
  { name: "SSO", category: "backend", aliases: ["Single sign-on", "SAML"] },
  { name: "Serverless", category: "backend" },
  { name: "Prisma", category: "backend" },
  { name: "Supabase", category: "backend" },
  { name: "Firebase", category: "backend" },

  // Data
  { name: "PostgreSQL", category: "data", aliases: ["Postgres"] },
  { name: "MySQL", category: "data" },
  { name: "SQL Server", category: "data", aliases: ["MSSQL"] },
  { name: "Oracle", category: "data" },
  { name: "SQLite", category: "data" },
  { name: "MongoDB", category: "data", aliases: ["Mongo"] },
  { name: "DynamoDB", category: "data" },
  { name: "Cassandra", category: "data" },
  { name: "Redis", category: "data" },
  { name: "Elasticsearch", category: "data", aliases: ["Elastic search", "OpenSearch"] },
  { name: "NoSQL", category: "data" },
  { name: "Schema design", category: "data", aliases: ["Data modeling", "Data modelling"] },
  { name: "Snowflake", category: "data" },
  { name: "BigQuery", category: "data" },
  { name: "Redshift", category: "data" },
  { name: "Databricks", category: "data" },
  { name: "Spark", category: "data", aliases: ["Apache Spark", "PySpark"] },
  { name: "Hadoop", category: "data" },
  { name: "Airflow", category: "data", aliases: ["Apache Airflow"] },
  { name: "dbt", category: "data", caseSensitive: true },
  { name: "ETL", category: "data", aliases: ["ELT", "Data pipelines", "Data pipeline"] },
  { name: "Pandas", category: "data" },
  { name: "NumPy", category: "data" },
  { name: "Tableau", category: "data" },
  { name: "Power BI", category: "data", aliases: ["PowerBI"] },
  { name: "Data visualization", category: "data", aliases: ["Data visualisation"] },
  { name: "Excel", category: "data", aliases: ["Microsoft Excel"], caseSensitive: true },

  // Cloud & DevOps
  { name: "AWS", category: "cloud", aliases: ["Amazon Web Services"] },
  { name: "Azure", category: "cloud", aliases: ["Microsoft Azure"] },
  { name: "GCP", category: "cloud", aliases: ["Google Cloud", "Google Cloud Platform"] },
  { name: "EC2", category: "cloud", caseSensitive: true },
  { name: "S3", category: "cloud", caseSensitive: true },
  { name: "Lambda", category: "cloud", aliases: ["AWS Lambda"] },
  { name: "RDS", category: "cloud", caseSensitive: true },
  { name: "IAM", category: "cloud", caseSensitive: true },
  { name: "CloudWatch", category: "cloud" },
  { name: "CloudFormation", category: "cloud" },
  { name: "ECS", category: "cloud", caseSensitive: true },
  { name: "EKS", category: "cloud", caseSensitive: true },
  { name: "Docker", category: "cloud", aliases: ["Containers", "Containerization"] },
  { name: "Kubernetes", category: "cloud", aliases: ["K8s"] },
  { name: "Helm", category: "cloud", caseSensitive: true },
  { name: "Terraform", category: "cloud" },
  { name: "Ansible", category: "cloud" },
  { name: "Infrastructure as code", category: "cloud", aliases: ["IaC"] },
  { name: "CI/CD", category: "cloud", aliases: ["CI CD", "Continuous integration", "Continuous delivery", "Continuous deployment"] },
  { name: "Jenkins", category: "cloud" },
  { name: "GitHub Actions", category: "cloud" },
  { name: "GitLab CI", category: "cloud", aliases: ["GitLab"] },
  { name: "Linux", category: "cloud", aliases: ["Unix"] },
  { name: "Nginx", category: "cloud" },
  { name: "Vercel", category: "cloud" },
  { name: "Observability", category: "cloud", aliases: ["Monitoring", "Logging", "Alerting"] },
  { name: "Datadog", category: "cloud" },
  { name: "Prometheus", category: "cloud" },
  { name: "Grafana", category: "cloud" },
  { name: "Splunk", category: "cloud" },
  { name: "Sentry", category: "cloud" },
  { name: "OpenTelemetry", category: "cloud" },
  { name: "Networking", category: "cloud", aliases: ["TCP/IP", "DNS", "HTTP", "TLS"] },

  // AI & ML
  { name: "Machine learning", category: "ai", aliases: ["ML"] },
  { name: "Deep learning", category: "ai" },
  { name: "LLMs", category: "ai", aliases: ["LLM", "Large language models", "Large language model", "LLM APIs"] },
  { name: "RAG", category: "ai", aliases: ["Retrieval augmented generation", "Retrieval-augmented generation"] },
  { name: "Embeddings", category: "ai", aliases: ["Embedding"] },
  { name: "Vector databases", category: "ai", aliases: ["Vector database", "Vector DB", "Vector search", "Pinecone", "pgvector"] },
  { name: "Prompt engineering", category: "ai" },
  { name: "NLP", category: "ai", aliases: ["Natural language processing"] },
  { name: "Computer vision", category: "ai" },
  { name: "PyTorch", category: "ai" },
  { name: "TensorFlow", category: "ai" },
  { name: "scikit-learn", category: "ai", aliases: ["sklearn"] },
  { name: "LangChain", category: "ai" },
  { name: "LangGraph", category: "ai" },
  { name: "Hugging Face", category: "ai", aliases: ["HuggingFace", "Transformers"] },
  { name: "OpenAI", category: "ai", aliases: ["GPT"] },
  { name: "AWS Bedrock", category: "ai", aliases: ["Bedrock"] },
  { name: "AI agents", category: "ai", aliases: ["Agentic", "Agentic AI", "AI agent"] },
  { name: "MLOps", category: "ai" },

  // Testing
  { name: "Unit testing", category: "testing", aliases: ["Unit tests"] },
  { name: "Integration testing", category: "testing", aliases: ["Integration tests"] },
  { name: "End-to-end testing", category: "testing", aliases: ["E2E testing", "E2E tests", "End to end tests"] },
  { name: "Test automation", category: "testing", aliases: ["Automated testing"] },
  { name: "TDD", category: "testing", aliases: ["Test-driven development"] },
  { name: "Jest", category: "testing" },
  { name: "Cypress", category: "testing" },
  { name: "Playwright", category: "testing" },
  { name: "Selenium", category: "testing" },
  { name: "JUnit", category: "testing" },
  { name: "pytest", category: "testing" },
  { name: "Postman", category: "testing" },

  // Practices
  { name: "Agile", category: "practices", aliases: ["Scrum", "Kanban"] },
  { name: "Code review", category: "practices", aliases: ["Code reviews"] },
  { name: "Object-oriented programming", category: "practices", aliases: ["OOP", "Object oriented"] },
  { name: "Data structures", category: "practices" },
  { name: "Algorithms", category: "practices" },
  { name: "Design patterns", category: "practices" },
  { name: "Security", category: "practices", aliases: ["Secure coding", "Application security", "AppSec"] },
  { name: "Performance optimization", category: "practices", aliases: ["Performance tuning"] },
  { name: "Scalability", category: "practices", aliases: ["Scalable"] },
  { name: "Debugging", category: "practices", aliases: ["Troubleshooting"] },
  { name: "Documentation", category: "practices", aliases: ["Technical writing"] },
  { name: "Mentoring", category: "practices", aliases: ["Mentorship"] },

  // Tools
  { name: "Git", category: "tools" },
  { name: "GitHub", category: "tools" },
  { name: "Jira", category: "tools" },
  { name: "Confluence", category: "tools" },
  { name: "Figma", category: "tools" },
  { name: "n8n", category: "tools" },

  // Education
  { name: "Bachelor's degree", category: "education", aliases: ["Bachelor", "Bachelors", "B.S.", "BTech", "B.Tech"] },
  { name: "Master's degree", category: "education", aliases: ["Master", "Masters", "M.S."] },
  { name: "Computer science", category: "education", aliases: ["Computer Software Engineering", "Information Technology"] },
];
